# SQL Mastery Course - Beginner Level

Welcome! This notebook guides you through SQL basics using the course database.

## Setup: Connect to the Database

Run the cell below to connect to `sql_mastery.db`.

In [11]:
import sqlite3
import pandas as pd

DB_PATH = r'C:\Users\USER\Desktop\agentic ai\notebook_ds\sql_mastery_course\sql_mastery.db'
conn = sqlite3.connect(DB_PATH)
print(f"Connected to: {DB_PATH}")

def run_query(query):
    return pd.read_sql_query(query, conn)

# Test the connection
run_query("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;")

Connected to: C:\Users\USER\Desktop\agentic ai\notebook_ds\sql_mastery_course\sql_mastery.db

              name
0  airbnb_listings
1        customers
2      departments
3        employees
4           movies
5      order_items
6           orders
7         products

## Explore the Database

In [12]:
# See schema of employees
run_query("PRAGMA table_info(employees);")

   cid           name     type  notnull dflt_value  pk
0    0    employee_id  INTEGER        0       None   1
1    1     first_name     TEXT        1       None   0
2    2      last_name     TEXT        1       None   0
3    3          email     TEXT        0       None   0
4    4          phone     TEXT        0       None   0
5    5      hire_date     TEXT        0       None   0
6    6      job_title     TEXT        0       None   0
7    7         salary     REAL        0       None   0
8    8  department_id  INTEGER        0       None   0
9    9     manager_id  INTEGER        0       None   0

## SELECT & WHERE

In [13]:
# Basic SELECT
run_query("SELECT first_name, last_name, salary FROM employees LIMIT 10;")

  first_name last_name    salary
0       John     Smith   75000.0
1       Jane       Doe   95000.0
2        Bob   Johnson  110000.0
3      Alice  Williams  105000.0
4    Charlie     Brown   65000.0
5      Diana    Prince   85000.0
6     Edward    Norton  100000.0
7      Fiona     Apple   80000.0
8     George    Harris  200000.0
9     Hannah    Martin   60000.0

In [14]:
# WHERE filtering
run_query("SELECT * FROM employees WHERE salary >= 100000 ORDER BY salary DESC;")

,employee_id,first_name,last_name,email,phone,hire_date,job_title,salary,department_id,manager_id
0,9,George,Harris,george.harris@company.com,555-0109,2016-05-22,CTO,200000.0,2,NULL
1,15,Michael,Jordan,michael.jordan@company.com,555-0115,2017-09-19,Sales Manager,130000.0,6,NULL
2,3,Bob,Johnson,bob.johnson@company.com,555-0103,2020-01-10,Data Scientist,110000.0,1,1
3,4,Alice,Williams,alice.williams@company.com,555-0104,2017-11-05,Product Manager,105000.0,3,1
4,7,Edward,Norton,edward.norton@company.com,555-0107,2022-02-28,Data Engineer,100000.0,1,3

In [15]:
# Multiple conditions
run_query("""SELECT first_name, last_name, job_title, salary FROM employees WHERE department_id = 1 AND salary > 80000 ORDER BY salary DESC;""")

  first_name last_name       job_title    salary
0        Bob   Johnson  Data Scientist  110000.0
1     Edward    Norton   Data Engineer  100000.0

In [16]:
# LIKE wildcard
run_query("SELECT * FROM customers WHERE city LIKE 'N%';")

,customer_id,first_name,last_name,email,gender,age,city,state,registration_date,is_active
0,1,Sarah,Johnson,sarah.j@email.com,Female,28,New York,NY,2023-01-15,1
1,19,Harper,Lewis,harper.l@email.com,Female,25,Nashville,TN,2023-10-01,1

## ORDER BY, LIMIT, DISTINCT

In [17]:
# Top 5 highest paid
run_query("SELECT first_name, last_name, salary FROM employees ORDER BY salary DESC LIMIT 5;")

  first_name last_name    salary
0     George    Harris  200000.0
1    Michael    Jordan  130000.0
2        Bob   Johnson  110000.0
3      Alice  Williams  105000.0
4     Edward    Norton  100000.0

In [19]:
# DISTINCT departments
run_query("SELECT DISTINCT department_id FROM employees ORDER BY department_id;")

   department_id
0              1
1              2
2              3
3              4
4              5
5              6

## Aggregate Functions & GROUP BY

In [20]:
run_query("""SELECT COUNT(*) AS total_employees, AVG(salary) AS avg_salary, MIN(salary) AS min_salary, MAX(salary) AS max_salary FROM employees;""")

   total_employees    avg_salary  min_salary  max_salary
0               15  93333.333333     55000.0    200000.0

In [21]:
# Average salary by department
run_query("""SELECT department_id, COUNT(*) AS emp_count, ROUND(AVG(salary), 0) AS avg_salary FROM employees GROUP BY department_id ORDER BY avg_salary DESC;""")

   department_id  emp_count  avg_salary
0              2          4    113000.0
1              6          2    100000.0
2              3          2     92500.0
3              1          4     85000.0
4              5          1     78000.0
5              4          2     72500.0

In [22]:
# HAVING: depts with avg salary > 80k
run_query("""SELECT department_id, COUNT(*) AS emp_count, ROUND(AVG(salary), 0) AS avg_salary FROM employees GROUP BY department_id HAVING AVG(salary) > 80000 ORDER BY avg_salary DESC;""")

   department_id  emp_count  avg_salary
0              2          4    113000.0
1              6          2    100000.0
2              3          2     92500.0
3              1          4     85000.0

## 🎯 Practice Challenge

Try: 1) Customers >30 from CA. 2) Top 3 expensive products. 3) Movies per director. 4) Genres with avg rating > 8.0.

In [23]:
# Your practice space
run_query("SELECT * FROM customers LIMIT 5;")

,customer_id,first_name,last_name,email,gender,age,city,state,registration_date,is_active
0,1,Sarah,Johnson,sarah.j@email.com,Female,28,New York,NY,2023-01-15,1
1,2,Mike,Chen,mike.chen@email.com,Male,35,San Francisco,CA,2023-02-20,1
2,3,Emma,Davis,emma.d@email.com,Female,42,Chicago,IL,2023-03-10,1
3,4,Alex,Kumar,alex.k@email.com,Male,31,Austin,TX,2023-01-25,1
4,5,Olivia,Martinez,olivia.m@email.com,Female,26,Los Angeles,CA,2023-04-05,1

In [24]:
conn.close()
print("Connection closed.")

Connection closed.